### ISSUE TITLE
DocsModel.php at line 339

### ISSUE THREAD

**Issue by ghost** [phpnode/Yii-Docs-Generator#1]
docs check works just fine but I get an issue with actually building the documentation.

Command Issued:

``` bash
./yiic docs ../webroot noviews
```

Response Received:

``` bash
Building.. : Map Jungle Class Reference
Version... : 1.1.7
Source URL : 

Building model...

PHP Error[2]: Invalid argument supplied for foreach()
    in file /var/www/MapJungle.com/protected/commands/docs/DocsModel.php at line 339
#0 /var/www/MapJungle.com/protected/commands/docs/DocsModel.php(303): DocsModel->processMethod()
#1 /var/www/MapJungle.com/protected/commands/docs/DocsModel.php(144): DocsModel->processMethods()
#2 /var/www/MapJungle.com/protected/commands/docs/DocsModel.php(108): DocsModel->processClass()
#3 /var/www/MapJungle.com/protected/commands/docs/DocsModel.php(22): DocsModel->processClasses()
#4 /var/www/MapJungle.com/protected/commands/DocsCommand.php(307): DocsModel->build()
#5 /var/www/MapJungle.com/protected/commands/DocsCommand.php(152): DocsCommand->buildModel()
#6 /var/www/yii/framework/console/CConsoleCommandRunner.php(63): DocsCommand->run()
#7 /var/www/yii/framework/console/CConsoleApplication.php(88): CConsoleCommandRunner->run()
#8 /var/www/yii/framework/base/CApplication.php(155): CConsoleApplication->processRequest()
#9 /var/www/yii/framework/yiic.php(33): CConsoleApplication->run()
#10 /var/www/MapJungle.com/protected/yiic.php(7): require_once()
#11 /var/www/MapJungle.com/protected/yiic(4): require_once()
```

**Comment by phpnode** [comment]
Hi, yeah that's right, @input and @output tags will break things, you should be able to use @var or @param to document this depending on whether it's for a property or method
